"use client";
import { Poppins } from "next/font/google";
import "./globals.css";

const poopins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--pop",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Quizo</title>
      </head>
      <body className={`${poopins.className}`}>{children}</body>
    </html>
  );
}
